index:
    path:     /
    defaults: { _controller: DefaultController::indexAction }

registration:
    path:     /registration
    defaults: { _controller: RegistrationController::registrationAction }

home:
    path:     /home
    defaults: { _controller: DefaultController::homeAction }

logout:
    path:     /logout
    defaults: { _controller: DefaultController::logoutAction }

post:
    path:     /post
    defaults: { _controller: PostController::submitAction }

delete:
    path:     /delete/{id}
    defaults: { _controller: PostController::deleteAction }

edit:
    path:     /edit/{id}
    defaults: { _controller: PostController::editAction }
