index:
    path:     /
    defaults: { _controller: 'DefaultController::indexAction' }

registration:
    path:     /registration
    defaults: { _controller: 'RegistrationController::registrationAction' }
